[package]
name = "chip8"
version = "0.1.0"
authors = ["Shishir Gopinath"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
pixels = "0.3.0"
winit = "0.25.0"
cpal = "0.13.3"
static_assertions = "1.1.0"