[package]
name = "chip8"
version = "0.1.1"
authors = ["Shishir Gopinath"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
pixels = "0.13.0"
winit = "0.28.0"
cpal = "0.15.2"
static_assertions = "1.1.0"